server:
  port: 8080

spring:
  profiles:
    active: dev
   #接口返回对象中的日期格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
     url: jdbc:mysql://localhost:3306/testdb?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
     username: root
     password: root
     driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    mode: HTML
    #热部署文件，页面不产生缓存，及时更新
    cache: false
    prefix: classpath:templates/
    suffix: .html
    encoding: UTF-8
    enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jyl.jyl.domain